apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvcats
spec:
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage    
  capacity:
    storage: 2Gi
  hostPath:
    path: /mount-cats